---
# See https://developer.github.com/v3/repos/#edit for all available settings.

_extends: .github:.github/default-settings.yml

repository:
  name: partner-frontend
  description: ğŸ‘©â€ğŸ’¼ ğŸ¤ ğŸ‘¨â€ğŸ’¼ ğŸ’¬ ğŸ’¼ ğŸ“ˆ

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - 'ci/circleci: build'
          - 'ci/circleci: lint'
          - 'ci/circleci: test'
          # - 'ci/circleci: terraform_plan'
      required_pull_request_reviews:
        dismiss_stale_reviews: false
